apiVersion: v2
name: cluster-api-cleaner-vsphere
version: 0.4.1-dev
appVersion: 0.4.1-dev
description: "Operator for cleaning leftover Vsphere resources of workload clusters"
home: "https://github.com/giantswarm/cluster-api-cleaner-vsphere"
icon: https://s.giantswarm.io/app-icons/vsphere/1/icon-dark.png
annotations:
  application.giantswarm.io/team: "rocket"
  io.giantswarm.application.team: "rocket"
  config.giantswarm.io/version: 1.x.x
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/vmware-vsphere/1/logo_light.png
restrictions:
  compatibleProviders:
    - vsphere
